name: GH-Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: Ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install wasm binary toolchain
        run: sudo apt update && sudo apt install wabt binaryen

      - name: Setup Rust
        run: rustup target add wasm32-unknown-unknown

      - name: Compile
        run: make gh-pages
        
      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './public'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      
